<?php

declare(strict_types=1);

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use App\Repository\AmstRepository;
use App\Workflow\AmstWFDefinition;
use App\Workflow\AmstWorkflow;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\BabelBundle\Attribute\BabelStorage;
use Survos\BabelBundle\Contract\BabelHooksInterface;
use Survos\BabelBundle\Entity\Traits\BabelHooksTrait;
use Survos\MeiliBundle\Metadata\MeiliIndex;
use Survos\StateBundle\Traits\MarkingInterface;
use Survos\StateBundle\Traits\MarkingTrait;


use Survos\Lingua\Contracts\Attribute\Translatable;
use Survos\BabelBundle\Attribute\BabelLocale;
/**
 * @generated by code:entity from profile
 * @profile data/amst_en.profile.json
 */
#[Entity(repositoryClass: AmstRepository::class)]
#[MeiliIndex(
    ui: ['icon' => 'Amst'],
	primaryKey: 'code',
	filterable: self::FILTERABLE_FIELDS,
	sortable: self::SORTABLE_FIELDS,
	searchable: self::SEARCHABLE_FIELDS,
)]
#[BabelStorage()]
#[BabelLocale(locale: 'nl')]
#[ApiResource(
    operations: [
        new Get(),
        new GetCollection()
    ]
)]
final class Amst implements MarkingInterface, BabelHooksInterface
{
    use MarkingTrait;
    use BabelHooksTrait;

    public function __construct()
    {
        $this->marking = AmstWFDefinition::PLACE_NEW;
    }

	public const FILTERABLE_FIELDS = [
		'projectCode',
		'categorie',
		'fragmenten',
		'beginDat',
		'eindDat',
		'put',
		'vlak',
		'spoor',
		'niveau1',
		'niveau2',
		'niveau3',
		'niveau4',
		'website',
		'muntLandGeografisch',
		'muntAutoriteitPolitiek',
		'muntMuntsoort',
		'muntEenheidWaarde',
		'muntMuntplaatsProductieplaats',
		'muntLengteDiameterInMm',
		'citationUrl',
		'trefwoorden',
		'metaalGrootstehoogteMm',
		'image',
		'vlakMin',
		'vlakMax',
	];

	public const SORTABLE_FIELDS = ['vlakMax'];
	public const SEARCHABLE_FIELDS = [];

	/**
	 * Profile field "vondstnummer"
	 * @types string (storageHint=string)
	 * @stats total=5, nulls=0, distinct=5
	 * @length 15–16 chars
	 * @facetCandidate true
	 */
	#[Column(length: 32, nullable: true)]
	public ?string $vondstnummer = null;

	/**
	 * Profile field "projectCode"
	 * @original project_code
	 * @types string (storageHint=string)
	 * @stats total=5, nulls=0, distinct=1
	 * @length 4 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(length: 24, nullable: true)]
	public ?string $projectCode = null;

	/**
	 * Profile field "categorie"
	 * @types string (storageHint=string)
	 * @stats total=5, nulls=0, distinct=2
	 * @length 2–3 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(length: 3, nullable: true)]
	public ?string $categorie = null;


	/**
	 * Profile field "fragmenten"
	 * @types int (storageHint=int)
	 * @stats total=5, nulls=0, distinct=1
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $fragmenten = null;

	/**
	 * Profile field "beginDat"
	 * @original begin_dat
	 * @types int (storageHint=int)
	 * @stats total=3, nulls=0, distinct=3
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $beginDat = null;

	/**
	 * Profile field "eindDat"
	 * @original eind_dat
	 * @types int (storageHint=int)
	 * @stats total=3, nulls=0, distinct=3
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $eindDat = null;

	/**
	 * Profile field "put"
	 * @types int (storageHint=int)
	 * @stats total=5, nulls=0, distinct=2
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $put = null;

	/**
	 * Profile field "vlak"
	 * @types int, string (storageHint=string)
	 * @stats total=5, nulls=0, distinct=3
	 * @length 2 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(length: 2, nullable: true)]
	public ?string $vlak = null;

	/**
	 * Profile field "spoor"
	 * @types int (storageHint=int)
	 * @stats total=5, nulls=0, distinct=2
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $spoor = null;

	/**
	 * Profile field "niveau1"
	 * @types string (storageHint=string)
	 * @stats total=5, nulls=0, distinct=3
	 * @length 14–24 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */

	/**
	 * Profile field "niveau2"
	 * @types string (storageHint=string)
	 * @stats total=2, nulls=0, distinct=2
	 * @length 29–80 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */

	/**
	 * Profile field "niveau3"
	 * @types string (storageHint=string)
	 * @stats total=2, nulls=0, distinct=2
	 * @length 7–8 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */

	/**
	 * Profile field "niveau4"
	 * @types string (storageHint=string)
	 * @stats total=1, nulls=0, distinct=1
	 * @length 7 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */

	/**
	 * Profile field "website"
	 * @types int (storageHint=int)
	 * @stats total=5, nulls=0, distinct=2
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $website = null;

	/**
	 * Profile field "muntLandGeografisch"
	 * @original munt_land_geografisch
	 * @types string (storageHint=string)
	 * @stats total=1, nulls=0, distinct=1
	 * @length 11 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(length: 32, nullable: true)]
	public ?string $muntLandGeografisch = null;

	/**
	 * Profile field "muntAutoriteitPolitiek"
	 * @original munt_autoriteit_politiek
	 * @types string (storageHint=string)
	 * @stats total=1, nulls=0, distinct=1
	 * @length 8 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(length: 48, nullable: true)]
	public ?string $muntAutoriteitPolitiek = null;

	/**
	 * Profile field "muntMuntsoort"
	 * @original munt_muntsoort
	 * @types string (storageHint=string)
	 * @stats total=1, nulls=0, distinct=1
	 * @length 7 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(length: 48, nullable: true)]
	public ?string $muntMuntsoort = null;

	/**
	 * Profile field "muntEenheidWaarde"
	 * @original munt_eenheid_waarde
	 * @types int (storageHint=int)
	 * @stats total=1, nulls=0, distinct=1
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $muntEenheidWaarde = null;

	/**
	 * Profile field "muntMuntplaatsProductieplaats"
	 * @original munt_muntplaats_productieplaats
	 * @types string (storageHint=string)
	 * @stats total=1, nulls=0, distinct=1
	 * @length 8 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(length: 32, nullable: true)]
	public ?string $muntMuntplaatsProductieplaats = null;

	/**
	 * Profile field "muntLengteDiameterInMm"
	 * @original munt_lengte_diameter_in_mm
	 * @types int (storageHint=int)
	 * @stats total=1, nulls=0, distinct=1
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $muntLengteDiameterInMm = null;

	/**
	 * Profile field "citation_url"
	 * @types string (storageHint=string)
	 * @stats total=5, nulls=0, distinct=5
	 * @length 59–60 chars
	 * @facetCandidate true
	 */
	#[Column(length: 160, nullable: true)]
	public ?string $citationUrl = null;

	/**
	 * Profile field "code"
	 * @types string (storageHint=string)
	 * @stats total=5, nulls=0, distinct=5
	 * @length 15–16 chars
	 * @facetCandidate true
	 */
	#[Column(length: 22, nullable: false)] // now with prefix and hyphen
	#[Id]
	public ?string $code = null;

	/**
	 * Profile field "trefwoorden"
	 * @types string (storageHint=string)
	 * @stats total=1, nulls=0, distinct=1
	 * @length 26 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(length: 26, nullable: true)]
	public ?string $trefwoorden = null;

	/**
	 * Profile field "metaalGrootstehoogteMm"
	 * @original metaal_grootstehoogte_mm
	 * @types int (storageHint=int)
	 * @stats total=1, nulls=0, distinct=1
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $metaalGrootstehoogteMm = null;

	/**
	 * Profile field "image"
	 * @types string (storageHint=string)
	 * @stats total=1, nulls=0, distinct=1
	 * @length 77 chars
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(length: 255, nullable: true)]
	public ?string $image = null;

	/**
	 * Profile field "vlakMin"
	 * @original vlak_min
	 * @types int, float (storageHint=string)
	 * @stats total=3, nulls=0, distinct=3
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(length: 255, nullable: true)]
	public ?string $vlakMin = null;

	/**
	 * Profile field "vlakMax"
	 * @original vlak_max
	 * @types float (storageHint=float)
	 * @stats total=3, nulls=0, distinct=3
	 * @facetCandidate true
	 * @booleanLike true
	 */
	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $vlakMax = null;

        // <BABEL:TRANSLATABLE:START label>

    /**
     * Profile field "object"
     * @types string (storageHint=string)
     * @stats total=5, nulls=0, distinct=3
     * @length 4–13 chars
     * @facetCandidate true
     * @booleanLike true
     */

    #[Column(type: Types::STRING, length: 255, nullable: true)]
        private ?string $objectBacking = null;

        #[Translatable(context: NULL)]
        public ?string $object {
            get => $this->resolveTranslatable('object', $this->objectBacking, NULL);
            set => $this->objectBacking = $value;
        }
        // <BABEL:TRANSLATABLE:END label>

        // <BABEL:TRANSLATABLE:START description>
        #[Column(type: Types::TEXT, nullable: true)]
        private ?string $descriptionBacking = null;

        #[Translatable(context: NULL)]
        public ?string $description {
            get => $this->resolveTranslatable('description', $this->descriptionBacking, NULL);
            set => $this->descriptionBacking = $value;
        }
        // <BABEL:TRANSLATABLE:END description>
    /**
     * Profile field "subcategorie"
     * @types string (storageHint=string)
     * @stats total=5, nulls=0, distinct=3
     * @length 10–19 chars
     * @facetCandidate true
     * @booleanLike true
     */
    #[Column(length: 128, nullable: true)]
    private ?string $subcategorieBacking = null;

    #[Translatable(context: NULL)]
    public ?string $subcategorie {
        get => $this->resolveTranslatable('subcategorie', $this->subcategorieBacking);
        set =>
            $this->subcategorieBacking = $value;
    }



        // <BABEL:TRANSLATABLE:START niveau1>
        #[Column(type: Types::STRING, length: 255, nullable: true)]
        private ?string $niveau1Backing = null;

        #[Translatable(context: NULL)]
        public ?string $niveau1 {
            get => $this->resolveTranslatable('niveau1', $this->niveau1Backing, NULL);
            set => $this->niveau1Backing = $value;
        }
        // <BABEL:TRANSLATABLE:END niveau1>

        // <BABEL:TRANSLATABLE:START niveau2>
        #[Column(type: Types::STRING, length: 255, nullable: true)]
        private ?string $niveau2Backing = null;

        #[Translatable(context: NULL)]
        public ?string $niveau2 {
            get => $this->resolveTranslatable('niveau2', $this->niveau2Backing, NULL);
            set => $this->niveau2Backing = $value;
        }
        // <BABEL:TRANSLATABLE:END niveau2>

        // <BABEL:TRANSLATABLE:START niveau3>
        #[Column(type: Types::STRING, length: 255, nullable: true)]
        private ?string $niveau3Backing = null;

        #[Translatable(context: NULL)]
        public ?string $niveau3 {
            get => $this->resolveTranslatable('niveau3', $this->niveau3Backing, NULL);
            set => $this->niveau3Backing = $value;
        }
        // <BABEL:TRANSLATABLE:END niveau3>

        // <BABEL:TRANSLATABLE:START niveau4>
        #[Column(type: Types::STRING, length: 255, nullable: true)]
        private ?string $niveau4Backing = null;

        #[Translatable(context: NULL)]
        public ?string $niveau4 {
            get => $this->resolveTranslatable('niveau4', $this->niveau4Backing, NULL);
            set => $this->niveau4Backing = $value;
        }
        // <BABEL:TRANSLATABLE:END niveau4>
}
